export enum InstallErrorCode {
	ERROR_INTERNAL_ERROR = -100,
	ERROR_APP_NOT_OWNED = -10,
	ERROR_STORE_NOT_FOUND = -9,
	ERROR_INSTALL_IN_PROGRESS = -8,
	ERROR_DOWNLOAD_NOT_PRESENT = -7,
	ERROR_INSTALL_NOT_ALLOWED = -6,
	ERROR_INSTALL_UNAVAILABLE = -5,
	ERROR_INVALID_REQUEST = -4,
	ERROR_API_NOT_AVAILABLE = -3,
	ERROR_UNKNOWN = -2,
	NO_ERROR = 0,
}
