export { CanvasGradient } from './lib/CanvasGradient';
export { CanvasPattern } from './lib/CanvasPattern';
export { CanvasRenderingContext2D } from './lib/contexts/CanvasRenderingContext2D';
export { getOrCreateHTMLCanvasElement } from './lib/contextMapping';
export { DOMMatrix } from './lib/DOMMatrix';
export { DOMPoint } from './lib/DOMPoint';
export { HTMLCanvasElement } from './lib/HTMLCanvasElement';
export { Path2D } from './lib/Path2D';
export { TextMetrics } from './lib/TextMetrics';
