export { CanvasGradient } from './lib/CanvasGradient';
export { CanvasPattern } from './lib/CanvasPattern';
export { CanvasRenderingContext2D } from './lib/contexts/CanvasRenderingContext2D';
export { DOMMatrix } from './lib/DOMMatrix';
export { DOMPoint } from './lib/DOMPoint';
export { HTMLCanvasView } from './lib/html-canvas-view';
export { Path2D } from './lib/Path2D';
export { installPolyfills } from './lib/polyfills';
export { TextMetrics } from './lib/TextMetrics';
